version: "3.7"

services: 
  client:
    image: node:current-slim
    working_dir: /app
    volumes:
      - ./client/:/app
    ports:
      - 4200:4200
    command: sh -c "npm install && npm start"
  
  server:
    image: node:current-slim
    working_dir: /app
    volumes:
      - ./server/:/app
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000